apiVersion: apps/v1
kind: Deployment
metadata:
  name: as
  labels:
    app: as
spec:
  replicas: 3
  selector:
    matchLabels:
      app: as
  template:
    metadata:
      labels:
        app: as
    spec:
      containers:
      - name: autoscaling-app
        image: cakmadam/autoscaling-app:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        livenessProbe:
          httpGet:
            path: /app/health/
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /app/health/
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 5