apiVersion: apps/v1
kind: Deployment
metadata:
  name: as
  labels:
    app: as
spec:
  replicas: 3
  selector:
    matchLabels:
      app: as
  template:
    metadata:
      labels:
        app: as
    spec:
      containers:
      - name: autoscaling-app
        image: mtypey/kubernetes-app:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 75m
            memory: 15Mi
          limits: 
            cpu: 250m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 5
          timeoutSeconds: 4
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 5
          timeoutSeconds: 4
