apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: my-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       as
  updatePolicy:
    updateMode: "Auto"
  minAllowed:
    cpu: 75m
    memory: 15Mi