apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: as
spec:
  selector:
    app: as
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080