apiVersion: apps/v1
kind: Deployment
metadata:
  name: as
  labels:
    app: as
spec:
  replicas: 3
  selector:
    matchLabels:
      app: as
  template:
    metadata:
      labels:
        app: as
    spec:
      containers:
      - name: autoscaling-app
        image: mtypey/kubernetes-app:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            memory: 300Mi
          requests:
            memory: 50Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 5