apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: as-cpu
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: as
  metrics:
  - type: Resource 
    resource:
      name: memory
      targetAverageUtilization: 120
