apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: as-memory
spec:
  maxReplicas: 50
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: as
  metrics:
  - type: Resource 
    resource:
      name: memory
      target:
        type: Utilization
        averageValue: 120Mi
